command:

  # Delay required before a player can use RTP again.
  # Prevents players from spamming the command and generating too many chunks,
  # which could leave the world without valid locations.
  cooldown-between: 15 # in seconds


# Worlds reserved for RTP resources (do NOT create worlds with these names):
#   - resources_world (Overworld)
#   - resources_nether_world (Nether)
#   - resources_end_world (End)
# If you don't want a world to be used for RTP, simply avoid creating a world with its name.

world:

  # Number of pre-generated locations stored in a ring buffer so that when a player teleports,
  # the chunks of the chosen location have already been generated, resulting in an instant teleport.
  # Don't touch this if you don't know what you're doing!
  buffer-size: 100

  # The coordinates by which the player teleports to a world are between -range and +range.
  # Set a high value because resetting worlds requires manually creating a new world;
  # the plugin doesn't automatically create a new world because the worlds are huge,
  # and you'll only need to reset them after a long period of uptime.
  # Very large worlds were adopted in this plugin to ensure that the player
  # only teleports using /rtp to a chunk that has not yet been explored; guaranteeing a good player experience.
  generate-coordenates-range: 1_000_000


# Section to add support for random teleportation between different servers.
cross-server-support:

  # Enable this if you want random teleportation support between servers.
  # This option needs to be active on all servers with this plugin
  # (regardless of whether the server is secondary or primary).
  # Redis is required (install the Redis plugin and ensure Redis is running).
  enabled: false

  # Set this option to true if the server where this plugin is running does not have random teleport worlds.
  secondary-server: false

  # When the player types /rtp, the player will be redirected to server X, which is listed here.
  # Server X must have the random teleport plugin enabled, and the secondary-server option
  # on server X must be set to false.
  main-server-name: "smp"